language: csharp
solution: TestExamAssignment.sln

install:
  - nuget restore TestExamAssignment.sln
  - nuget install xunit.runners -Version 2.4.1 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release TestExamAssignment.sln
  - mono ./testrunner/xunit.runners.2.4.1/tools/xunit.console.clr4.exe ./TestExamAssignment.XTest/bin/Release/TestExamAssignment.XTest.dll