language: csharp
solution: TestExamAssignment.sln

install:
  - nuget restore TestExamAssignment.sln
  - nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release TestExamAssignment.sln
  - mono ./xunit.console.exe ./TestExamAssignment.XTest/bin/Release/TestExamAssignment.XTest.dll